aliases = [
  "modernizr:promises",
  "caniuse:promises",
  "blissfuljs",
  "default-3.4",
  "default-3.5",
  "default-3.6",
  "default",
  "es6",
  "es2015"
]
dependencies = [
  "AggregateError",
  "_ESAbstract.CreateDataProperty",
  "_ESAbstract.SpeciesConstructor",
  "_ESAbstract.OrdinaryObjectCreate",
  "_ESAbstract.CreateMethodProperty",
  "_ESAbstract.PromiseResolve",
  "_ESAbstract.Type",
  "_ESAbstract.IteratorClose",
  "_ESAbstract.NewPromiseCapability",
  "_ESAbstract.Invoke",
  "_ESAbstract.GetIterator",
  "_ESAbstract.CreateBuiltinFunction",
  "_ESAbstract.IsCallable",
  "_ESAbstract.OrdinaryCreateFromConstructor",
  "_ESAbstract.CreateResolvingFunctions",
  "_ESAbstract.Call",
  "_ESAbstract.IsConstructor",
  "_ESAbstract.Assert",
  "_ESAbstract.Get",
  "_ESAbstract.PromiseCapabilityRecord",
  "_ESAbstract.IteratorStep",
  "_ESAbstract.IteratorValue",
  "_ESAbstract.PerformPromiseThen",
]
notes = [
  "In IE8, the `catch` & `finally` method cannot be invoked directly since they are reserved words.  Instead, use `[\"catch\"]` and `[\"finally\"]` if intend to run your code in IE8"
]
license = "MIT"
docs = "https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise"

[browsers]
android = "*"
bb = "*"
chrome = "*"
edge = "*"
edge_mob = "*"
firefox = "*"
firefox_mob = "*"
ie = "*"
ie_mob = "*"
ios_chr = "*"
ios_saf = "*"
op_mini = "*"
op_mob = "*"
opera = "*"
safari = "*"
samsung_mob = "*"
