aliases = [
  "modernizr:urlparser",
  "blissfuljs",
  "default-3.4",
  "default-3.5",
  "default-3.6",
  "default",
  "URLSearchParams"
]
dependencies = [
  "String.prototype.codePointAt",
  "Object.assign",
  "Array.from",
  "Object.defineProperty",
  "Object.getPrototypeOf",
  "Object.keys",
  "Array.prototype.entries",
  "Symbol.iterator",
  "Reflect.has"
]
docs = "https://developer.mozilla.org/en-US/docs/Web/API/URL"

[browsers]
chrome = "<60"
firefox = "<44"
edge = "<18.17134"
edge_mob = "<17"
ie = "9 - *"
ie_mob = "*"
safari = "<12"
firefox_mob = "<44"
opera = "<36"
op_mini = "*"
android = "*"
samsung_mob = "<5"
bb = "*"
ios_saf = "<12"
