dependencies = [
  "Array.isArray",
  "Array.prototype.@@iterator",
  "Array.prototype.filter",
  "Array.prototype.forEach",
  "Array.prototype.indexOf",
  "Array.prototype.lastIndexOf",
  "Array.prototype.map",
  "Array.prototype.reduce",
  "Function.prototype.bind",
  "Intl.NumberFormat",
  "Intl.PluralRules",
  "Object.assign",
  "Object.create",
  "Object.defineProperty",
  "Object.is",
  "Object.keys",
  "Object.setPrototypeOf",
  "Symbol.iterator",
  "Symbol.toStringTag",
  "WeakMap"
]
license = "MIT"
spec = "https://tc39.es/proposal-intl-relative-time/#sec-intl-relativetimeformat-constructor"
repo = "https://github.com/formatjs/formatjs/tree/master/packages/intl-relativetimeformat/polyfill.js"
docs = "https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/RelativeTimeFormat"
notes = [
  "Locales must be specified separately by prefixing the locale name with `Intl.RelativeTimeFormat.~locale`, eg `Intl.RelativeTimeFormat.~locale.en-GB`."
]

[browsers]
android = "<63"
ie = "9 - *"
ie_mob = "9 - *"
edge = "<79"
edge_mob = "<79"
firefox = "<65"
opera = "<50"
chrome = "<71"
safari = "*"
ios_saf = "*"
firefox_mob = "<65"
samsung_mob = "<6"

[install]
module = "@formatjs/intl-relativetimeformat"
paths = [ "polyfill.umd.js" ]
postinstall = "update.task.js"

